# Generated by Django 6.0.2 on 2026-03-29 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('organizer', 'Organizer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
