# Generated by Django 6.0.2 on 2026-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventproposal',
            name='description',
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
