# Generated by Django 6.0.1 on 2026-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_date_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('announced', 'Announced'), ('completed', 'Completed')], default='created', max_length=20),
        ),
    ]
