# Generated by Django 6.0.2 on 2026-03-22 09:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventproposal_status_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'student')},
        ),
    ]
