# Generated by Django 6.0.2 on 2026-03-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventregistration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproposal',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
