# Generated by Django 6.0.2 on 2026-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventproposal_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Announced', 'Announced'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
