# Generated by Django 6.0.2 on 2026-04-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_created_at_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Announced', 'Announced'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
