# Generated by Django 6.0.1 on 2026-04-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='registered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventproposal',
            name='number',
        ),
    ]
