# Generated by Django 6.0.1 on 2026-04-11 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_registered_at_eventregistration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventproposal',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
