# Generated by Django 6.0.2 on 2026-04-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproposal',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
