# Generated by Django 6.0.2 on 2026-04-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_notification_announcement_notification_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Announced', 'Announced'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
