# Generated by Django 6.0.2 on 2026-04-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Accepted', 'Accepted'), ('Announced', 'Announced'), ('Completed', 'Completed')], default='Created', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
