# Generated by Django 6.0.2 on 2026-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_feedback_experience_alter_feedback_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('event_assigned', 'Event Assigned'), ('event_announced', 'Event Announced'), ('event_completed', 'Event Completed'), ('announcement', 'Announcement')], max_length=50, null=True),
        ),
    ]
