# Generated by Django 6.0.2 on 2026-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('event_assigned', 'Event Assigned'), ('event_announced', 'Event Announced'), ('event_completed', 'Event Completed'), ('announcement', 'Announcement'), ('general', 'General')], default='general', max_length=50, null=True),
        ),
    ]
