# Generated by Django 6.0.1 on 2026-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_notification_action_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('announced', 'Announced'), ('completed', 'Completed')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='experience',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_assigned', 'Event Assigned'), ('event_announced', 'Event Announced'), ('event_completed', 'Event Completed'), ('announcement', 'Announcement'), ('feedback', 'Feedback'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
