# Generated by Django 6.0.2 on 2026-05-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_eventreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='event',
        ),
    ]
