# Generated by Django 6.0.2 on 2026-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_eventregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventreport',
            options={},
        ),
    ]
