# Generated by Django 6.0.2 on 2026-05-03 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_eventreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.event'),
        ),
    ]
