# Generated by Django 6.0.2 on 2026-05-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_eventreport_options_alter_eventreport_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.event'),
        ),
    ]
